services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # e.g. write /bytestash for a domain such as my.domain/bytestash, leave blank in every other case
      - BASE_PATH=
      # Either provide JWT_SECRET directly or use JWT_SECRET_FILE for Docker secrets
      #- JWT_SECRET_FILE=/run/secrets/jwt
      - JWT_SECRET=your-secret
      # how long the token lasts, examples: "2 days", "10h", "7d", "1m", "60s"
      - TOKEN_EXPIRY=24h
      # is this bytestash instance open to new accounts being created?
      - ALLOW_NEW_ACCOUNTS=true
      # Should debug mode be enabled? Essentially enables logging, in most cases leave this as false
      - DEBUG=false
    volumes:
      - ./data:/data/snippets
# Uncomment to use docker secrets
#    secrets:
#      - jwt

#secrets:
#  jwt:
#    file: ./secrets/jwt.txt