CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    username_normalized TEXT,
    password_hash TEXT NOT NULL,
    oidc_id TEXT,
    oidc_provider TEXT,
    email TEXT,
    name TEXT,
    created_at TIMESTAMP(0) DEFAULT (now() AT TIME ZONE 'utc'),
    is_admin SMALLINT DEFAULT 0,
    last_login_at TIMESTAMP(0),
    is_active SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS snippets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP(0) DEFAULT (now() AT TIME ZONE 'utc'),
    expiry_date TIMESTAMP(0) DEFAULT NULL,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    is_public SMALLINT DEFAULT 0,
    is_pinned SMALLINT DEFAULT 0,
    is_favorite SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snippet_id INTEGER REFERENCES snippets (id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS fragments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snippet_id INTEGER NOT NULL REFERENCES snippets (id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    code TEXT NOT NULL,
    language TEXT NOT NULL,
    position INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS shared_snippets (
    id TEXT PRIMARY KEY,
    snippet_id INTEGER NOT NULL REFERENCES snippets (id) ON DELETE CASCADE,
    requires_auth SMALLINT NOT NULL DEFAULT 0,
    expires_at TIMESTAMP(0),
    created_at TIMESTAMP(0) DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS api_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP(0) DEFAULT (now() AT TIME ZONE 'utc'),
    last_used_at TIMESTAMP(0),
    is_active SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id INTEGER PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    settings TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMP(0) DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_snippets_user_id ON snippets (user_id);

CREATE INDEX IF NOT EXISTS idx_snippets_is_public ON snippets (is_public);

CREATE INDEX IF NOT EXISTS idx_snippets_user_expiry ON snippets (user_id, expiry_date);

CREATE INDEX IF NOT EXISTS idx_snippets_user_updated ON snippets (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_snippets_updated_at ON snippets (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_categories_snippet_id ON categories (snippet_id);

CREATE INDEX IF NOT EXISTS idx_categories_name ON categories (name);

CREATE INDEX IF NOT EXISTS idx_fragments_snippet_id ON fragments (snippet_id);

CREATE INDEX IF NOT EXISTS idx_fragments_language ON fragments (language);

CREATE INDEX IF NOT EXISTS idx_shared_snippets_snippet_id ON shared_snippets (snippet_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_normalized ON users (LOWER(username_normalized));

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_oidc ON users (oidc_id, oidc_provider)
WHERE
    oidc_id IS NOT NULL
    AND oidc_provider IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON api_keys (user_id);
